version: "3"
services:
##Serviço 1 - Moodle
  moodle:                           # Nome do serviço
    container_name: "moodle"        # Nome do contêiner
    build:
      context: .
      dockerfile: Dockerfile-moodle
    depends_on:
        - mariadb
        - redis
    volumes:                        # Volumes persistentes utilizados
        - moodle_data:/bitnami/moodle 
    networks:                       # Redes utilizados pelo serviço
        - localhost
    ports:                          # Redirecionamento de portas
        - "127.0.0.1:8080:8080"
        - "127.0.0.1:8443:8443"
    environment:                    # Variáveis de ambiente
        - MOODLE_USERNAME=usuario
        - MOODLE_PASSWORD=moodle123
        - MOODLE_SITE_NAME=Moodle
        - MOODLE_DATABASE_NAME=moodledb
        - MOODLE_DATABASE_USER=moodledbuser
        - MOODLE_DATABASE_PASSWORD=moodledbpassword
        
##Serviço 2 - Banco de Dados
  mariadb:
    container_name: "mariadb"
    image: bitnami/mariadb
    volumes:
        - database:/bitnami/mariadb
    networks:
        - localhost
    ports:
        - "127.0.0.1:3306:3306"
    environment:
        - MARIADB_DATABASE=moodledb
        - MARIADB_ROOT_USER=moodledbuser
        - MARIADB_ROOT_PASSWORD=moodledbpassword

##Serviço 3 - Servico de Cache
  redis:
    container_name: "redis"
    image: bitnami/redis
    volumes:
        - redis:/bitnami/redis/data
    networks:
        - localhost
    ports:
        - "127.0.0.1:6379:6379"
    environment:
        - REDIS_PASSWORD=moddleredispassword
      
##Serviço 4 - API de Machine Learning
  machinelearning:
    container_name: "machinelearning"
    image: moodlehq/moodle-mlbackend-python:2.4.0-python3.7.5 
    depends_on:
        - moodle
    volumes:
        - ml_data:/opt/mlbackenddata
    networks:
        - localhost
    ports:
        - "127.0.0.1:5000:5000"

volumes:                            # Definição dos volumes persistentes
        moodle_data:
        database:
        redis:
        ml_data:
networks:                           # Definição das redes
        localhost: