##ADAPTADO DE  : https://github.com/ceefour/bitnami-docker-moodle/

FROM bitnami/moodle:latest

# Configurar PHP error_log para stderr
RUN echo "error_log = /dev/stderr" > /opt/bitnami/php/etc/conf.d/error_log.ini

# Habilitar opcache
#RUN sed -i 's/opcache.enable = Off/opcache.enable = 1/I' /opt/bitnami/php/etc/php.ini
RUN echo "opcache.enable = 1" > /opt/bitnami/php/etc/conf.d/opcache.ini

# Preparar PECL build tools
RUN apt-get update && \
    apt-get install -y gcc make autoconf libc-dev libssl-dev pkg-config

# Instalar PECL igbinary
# igbinary serializer & lzf compression is recommended: https://pdfs.semanticscholar.org/8395/e04cf62d03597e2a2e6a605ebc52bfa6ca7d.pdf 
RUN pecl channel-update pecl.php.net && \
    pecl install igbinary
RUN echo "extension=igbinary.so" > /opt/bitnami/php/etc/conf.d/igbinary.ini

# Instalar PECL redis
RUN pecl channel-update pecl.php.net
RUN pecl install redis
RUN echo "extension=redis.so" > /opt/bitnami/php/etc/conf.d/redis.ini